// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx-UhOexYGMKKa4yTRLUaq_yirHZI8SHE',
    appId: '1:349462773507:web:8941630d2f868d85247336',
    messagingSenderId: '349462773507',
    projectId: 'matacare-94d0d',
    authDomain: 'matacare-94d0d.firebaseapp.com',
    storageBucket: 'matacare-94d0d.appspot.com',
    measurementId: 'G-3GGZPXK879',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtG_ZCMJTM3LTtCEV5wyHWnDobRdFUab4',
    appId: '1:349462773507:android:e82f219429a4fcc7247336',
    messagingSenderId: '349462773507',
    projectId: 'matacare-94d0d',
    storageBucket: 'matacare-94d0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI5vuPNjCb0p-pnfl1xNeCyA1HQ_gz5PM',
    appId: '1:349462773507:ios:b84aad1e7ac485f7247336',
    messagingSenderId: '349462773507',
    projectId: 'matacare-94d0d',
    storageBucket: 'matacare-94d0d.appspot.com',
    iosClientId:
        '349462773507-ttobdjuq0k7u9irdepj0rob3km19825j.apps.googleusercontent.com',
    iosBundleId: 'com.matacare.mobile',
  );
}
